name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-deploy
          chmod 600 ~/.ssh/github-actions-deploy

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: clinic-api
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to server
        run: |
          scp -i ~/.ssh/github-actions-deploy \
            -o StrictHostKeyChecking=no \
            clinic-api.tar.gz \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/tmp/clinic-api.tar.gz

      - name: ssh to server
        run: |
          ssh -i ~/.ssh/github-actions-deploy \
          -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} \
          "mkdir -p /var/www/deployment-project \
          tar -xzf /tmp/deployment-project.tar.gz -C /home/ubuntu/deployment-project \
          cd /home/ubuntu/deployment-project && npm ci --omit=dev \
          sudo systemctl restart deployment-project"
