name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create artifact
        run: |
          mkdir package
          cp -r dist package/
          cp -r prisma package/
          cp package.json package/
          cp package-lock.json package/

          tar -czf clinic-api.tar.gz -C package .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clinic-api
          path: clinic-api.tar.gz
